version: '3'

services:
  database:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile_mysql
    image: 'mysql_school:latest'
    restart: always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'
