version: '3'

services:
  database:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile_mysql
    image: 'mysql_school:latest'
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    restart: always
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - '3306:3306'

# UTF8 coding - https://stackoverflow.com/questions/62019044/mysql-change-charset-to-utf-8