version: '3'

services:
  database:
    platform: linux/x86_64
    build:
      context: .
      dockerfile: docker_mysql
    image: 'mysql_ls:latest'
    restart: always
    container_name: db_school
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_school
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - '3306:3306'
