-- MySQL Script generated by MySQL Workbench
-- Sat Jan  2 11:10:44 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema test3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema test3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `test3` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `test3` ;

-- -----------------------------------------------------
-- Table `test3`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`role` (
                                              `id_role` INT NOT NULL AUTO_INCREMENT,
                                              `description` VARCHAR(100) NULL,
    PRIMARY KEY (`id_role`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`user` (
                                              `id_user` INT NOT NULL AUTO_INCREMENT,
                                              `name` VARCHAR(45) NULL,
    `surname` VARCHAR(45) NULL,
    `email` VARCHAR(45) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `id_role` INT NOT NULL,
    PRIMARY KEY (`id_user`, `id_role`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
    INDEX `fk_user_role1_idx` (`id_role` ASC) VISIBLE,
    CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`id_role`)
    REFERENCES `test3`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`teaching_lang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`teaching_lang` (
                                                       `id_teaching_lang` INT NOT NULL AUTO_INCREMENT,
                                                       `code` VARCHAR(3) NULL,
    `name` VARCHAR(45) NULL,
    PRIMARY KEY (`id_teaching_lang`),
    UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`course` (
                                                `id_course` INT NOT NULL AUTO_INCREMENT,
                                                `points` INT NOT NULL DEFAULT 0,
                                                `native_lang` VARCHAR(20) NULL,
    `teaching_lang` VARCHAR(20) NULL,
    `description` VARCHAR(45) NULL,
    `id_teaching_lang` INT NOT NULL,
    `id_user` INT NOT NULL,
    `id_role` INT NOT NULL,
    PRIMARY KEY (`id_course`, `id_teaching_lang`),
    INDEX `fk_course_teaching_lang1_idx` (`id_teaching_lang` ASC) VISIBLE,
    INDEX `fk_course_user1_idx` (`id_user` ASC, `id_role` ASC) VISIBLE,
    CONSTRAINT `fk_course_teaching_lang1`
    FOREIGN KEY (`id_teaching_lang`)
    REFERENCES `test3`.`teaching_lang` (`id_teaching_lang`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_course_user1`
    FOREIGN KEY (`id_user` , `id_role`)
    REFERENCES `test3`.`user` (`id_user` , `id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`question` (
                                                  `id_question` INT NOT NULL AUTO_INCREMENT,
                                                  `question` VARCHAR(1500) NOT NULL,
    `answ1` VARCHAR(250) NULL,
    `answ2` VARCHAR(250) NULL,
    `answ3` VARCHAR(250) NULL,
    `points` INT NOT NULL,
    `answ4` VARCHAR(250) NULL,
    PRIMARY KEY (`id_question`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`test` (
                                              `id_test` INT NOT NULL AUTO_INCREMENT,
                                              `question_count` INT NULL,
                                              `user_id_user` INT NOT NULL,
                                              `user_id_role` INT NOT NULL,
                                              PRIMARY KEY (`id_test`),
    INDEX `fk_test_user1_idx` (`user_id_user` ASC, `user_id_role` ASC) VISIBLE,
    CONSTRAINT `fk_test_user1`
    FOREIGN KEY (`user_id_user` , `user_id_role`)
    REFERENCES `test3`.`user` (`id_user` , `id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`test_to_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`test_to_question` (
                                                          `id_test_to_question` INT NOT NULL AUTO_INCREMENT,
                                                          `id_test` INT NOT NULL,
                                                          `id_question` INT NOT NULL,
                                                          PRIMARY KEY (`id_test_to_question`, `id_test`, `id_question`),
    INDEX `fk_test_to_question_test1_idx` (`id_test` ASC) VISIBLE,
    INDEX `fk_test_to_question_question1_idx` (`id_question` ASC) VISIBLE,
    CONSTRAINT `fk_test_to_question_test1`
    FOREIGN KEY (`id_test`)
    REFERENCES `test3`.`test` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_test_to_question_question1`
    FOREIGN KEY (`id_question`)
    REFERENCES `test3`.`question` (`id_question`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `test3`.`course_to_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `test3`.`course_to_test` (
                                                        `id_course_to_test` INT NOT NULL,
                                                        `id_course` INT NOT NULL,
                                                        `id_test` INT NOT NULL,
                                                        PRIMARY KEY (`id_course_to_test`, `id_course`, `id_test`),
    INDEX `fk_course_to_test_course1_idx` (`id_course` ASC) VISIBLE,
    INDEX `fk_course_to_test_test1_idx` (`id_test` ASC) VISIBLE,
    CONSTRAINT `fk_course_to_test_course1`
    FOREIGN KEY (`id_course`)
    REFERENCES `test3`.`course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_course_to_test_test1`
    FOREIGN KEY (`id_test`)
    REFERENCES `test3`.`test` (`id_test`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
